### ISSUE TITLE
Refactor forEach/push usage to use the array map function instead

### ISSUE THREAD

**Issue by ChopsMcGee** [isabelramos/this-aint-your-mamas-records#9]
https://github.com/isabelramos/this-aint-your-mamas-records/blob/89311720a475435b26618a423a66d34a047b05cc/public/javascripts/factories/UserFactory.js#L41

Hello - this is Richard from Arbor/Equian again.

A lot of the time when you see a forEach function that is simply used to push items onto a new array, you can refactor that code to use the array map function instead of the array forEach function. Could you try refactoring this to use the array map function instead of the array forEach function? Here is a page that shows how to use that map function: https://www.w3schools.com/jsref/jsref_map.asp

So if you were to redefine this loop as:
```
let userKeys = Object.keys(userObject.data);
let users = userKeys.map((key) => {
   ...your code here...
});
```
...then you will still have the key object defined inside of your map function like you had inside of your forEach function, but your map function will need to return the value that you want to add to the users array, instead of using users.push() as you are doing here. That is the beauty of the array map function! Give it a try, and let me know in the next day or so how it goes!

**Comment by isabelthedesigner** [comment]
Hi Richard! I just saw you had opened these issues (I was working on another minor feature for the project just now) so I will definitely try implementing the array map function and see how it turns out. Thank you!

**Comment by ChopsMcGee** [comment]
Excellent! I hope you enjoy seeing the map function in action!

**Comment by isabelthedesigner** [comment]
Hi Richard! I'm trying to get the map function working on the getAllUsers() function in my UserFactory.js and I tried a few things but I think the following code is more along the lines of what I'm going for since I'm trying to return the values of all the keys in the object:

```  
let userKeys = Object.keys(userObject.data);
     let users = userKeys.map((key) => {
         return {
            uid: key.uid,
            profile_pic: key.profile_pic,
            username: key.username
          };
      });
``` 

When I console log it, it's structured the way I want but the values come back as undefined so I'm not sure why that is. Let me know your thoughts on how I should go about rectifying this when you get a chance. Thanks!

**Comment by ChopsMcGee** [comment]
Hi again Isabel! See if the following value inside of the map function has any of the data that you are looking for (this might not be exactly right, since I have not tried running it on my local machine):

```
userObject.data[key]
```

You might be able to just return that value from the map function I think? Tinker with it and see if it gives you something good.

**Comment by isabelthedesigner** [comment]
That did the trick, thank you! I'm now working on implementing the map function to the getRecordList function in my RecordFactory.js. It's slightly different so I'll see if I can get that to work as well. Thanks!

**Comment by ChopsMcGee** [comment]
Excellent news! Yeah in addition to forEach and map, there's a whole new world of array functions like filter, find, and reduce that can really come in handy sometimes!
